### ISSUE TITLE
Foreslå og forankre nye tilgangsgrupper hos interessenter

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-groups#7]
Forslag sendt på høring ligger [her](https://docs.altinn.studio/authorization/modules/accessgroups/type-accessgroups/)

Høring versjon 1 ble avsluttet 1.8.23
Høring versjon 2 sendes ut medio september og har frist 10.11.23

Arbeidsdokument for videre arbeid ligger i dette [excelarket](https://digdir.sharepoint.com/:x:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Nye%20tilgangsgrupper/Oversikt%20nye%20tilgangsgrupper.xlsx?d=w32e0635ad4594f44a3cc49d45241ed40&csf=1&web=1&e=CSxphc) (krever tilgang)

```[tasklist]
### Tasks
- [x] Ferdigstill forslag som kan sendes på høring
- [x] Send ut forslag på høring
- [x] Ta imot innspill og oppdater forslag
- [x] Gi fullmaktsgrupper en beskrivelse
- [ ] Avklar hvilke ER roller som skal benyttes og hva de skal få tilgang til på vegne av virksomhet
- [x] Lag bedre dokumentasjon til tjenesteeiere som svar på spørsmål
- [x] Gjennomfør høring nr 2
```

Oppgaven er del av [#altinn-access-management/issues/341](https://github.com/Altinn/altinn-access-management/issues/341) og https://github.com/Altinn/altinn-roadmap/issues/63
```[tasklist]
### Innspill som må følges opp
- [x] Endre navn på Patent-tilgangsgruppe
- [x] Diskuter tilgangsgruppe knyttet til statistikkrapportering, SSB: https://github.com/Altinn/altinn-support-private/issues/1344
- [x] Vurder annet navn på rollen for kommunale sider: https://github.com/Altinn/altinn-support-private/issues/1285
- [x] Vurdere innspill fra DIBK: https://github.com/Altinn/altinn-support-private/issues/1529
- [x] Vurdere innspill fra helsedirektoratet: https://github.com/Altinn/altinn-support-private/issues/1502
- [x] Behandle innspill fra SSB: https://github.com/Altinn/altinn-support-private/issues/1536
- [x] Behandle innspill fra Patentstyret: https://github.com/Altinn/altinn-support-private/issues/1311
- [x] Behandle innspill fra Statens pensjonskasse: https://github.com/Altinn/altinn-support-private/issues/1387
- [x] Behandle innspill fra Havforskningsinstituttet: https://github.com/Altinn/altinn-support-private/issues/1388
- [x] Behandle innspill fra Sjøfartsdiektoratet: https://github.com/Altinn/altinn-support-private/issues/1427 og https://github.com/Altinn/altinn-support-private/issues/1471
- [x] Behandle innspill fra Udir: https://github.com/Altinn/altinn-support-private/issues/1458
- [x] Behandle tilbakemelding fra NAV: https://github.com/Altinn/altinn-support-private/issues/1490
- [x] Behandle innspill fra oslo kommune: https://github.com/Altinn/altinn-support-private/issues/1497
- [x] Behandle innspill fra Politiets IT-enhet: https://github.com/Altinn/altinn-support-private/issues/1575
- [x] Behandle innspill fra SVV: https://github.com/Altinn/altinn-support-private/issues/1645
- [x] Behandle innspill fra valgdirektoratet: https://github.com/Altinn/altinn-support-private/issues/1581
- [x] Behandle innspill fra Økokrim: https://github.com/Altinn/altinn-support-private/issues/1604
- [x] Behandle innspill fra Kulturdirektoratet https://github.com/Altinn/altinn-support-private/issues/1743
```
Innspill er gjennomgått og lagt inn i [regneark](https://digdir.sharepoint.com/:x:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Nye%20tilgangsgrupper/Oversikt%20nye%20tilgangsgrupper.xlsx?d=w32e0635ad4594f44a3cc49d45241ed40&csf=1&web=1&e=CSxphc) "til diskusjon_revidert" 
```[tasklist]
### Innspill til behandling høringsrunde 2
- [x] https://github.com/Altinn/altinn-support-private/issues/2147 - Legemiddelverket
- [x] https://github.com/Altinn/altinn-support-private/issues/2040 - Nkom
- [x] https://github.com/Altinn/altinn-support-private/issues/2036 - Skatt
- [x] https://github.com/Altinn/altinn-support-private/issues/2159 - Valg
- [x] https://github.com/Altinn/altinn-support-private/issues/2165 - SFD
- [x] https://github.com/Altinn/altinn-support-private/issues/2186 - NOKUT
- [x] https://github.com/Altinn/altinn-support-private/issues/2192 - Udir
- [x] https://github.com/Altinn/altinn-support-private/issues/2190 - BRG
- [x] https://github.com/Altinn/altinn-support-private/issues/2188 - SSB
```

**Comment by rtafj** [comment]
Oversikt over rettighetspakkene som skal legges inn i ressursregisteret som første versjon, finnes her; https://digdir.sharepoint.com/:x:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Nye%20tilgangsgrupper/rettighetspakker%20oversikt.xlsx?d=w453ebbd31eec4bb28a86798c099f6ba2&csf=1&web=1&e=vfTvCp
